modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Cheese Ez"
description = '''
Just Enough Juice Mod adds various types of juices to Minecraft that give you custom powers.
'''
logoFile = "logo.png"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
